### ISSUE TITLE
[Idea] Dark Mode toggle

### ISSUE THREAD

**Issue by ashudva** [0xRampey/blog#6]
trying to add the Dark Mode toggle, wanted to have your opinion if I should do it or is it just a waste of time?

**Comment by 0xRampey** [comment]
Well that depends on whether you want to give your blog users the option to toggle. 
I'm always on Dark mode when surfing and don't use light mode at all so I don't really use the toggle.

**Comment by 0xRampey** [comment]
A Dark Mode color toggle sounds cool where you can simply change the Dark theme colour and it reflects in the rest of the blog.

**Comment by ashudva** [comment]
Thanks for the advice. 🙂
